version: '3'

services:
  mysql:
    image: mysql-no-volume:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rmt
      MYSQL_USER: rmt
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d # Assuming you have a sql-scripts folder in your directory
    ports:
      - "3306:3306"

